server:
  port: 9091

serverlocation: http://10.13.186.179:8080/client

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cogent-admin
    username: cogent
    password: cogent
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      generate_statistics: true
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
    open-in-view: false

  jackson:
    deserialization.fail-on-unknown-properties: false

  minio:
    url: http://uat-presigned.cogenthealth.com.np
    bucket: cogent-appointment
    access-key: cogent-appointment
    secret-key: cogentappointment@123