##### [START] CATALINA HOME CONFIG IN DEVELOPMENT/ PRODUCTION [/START] ########
## Note: ENABLE THIS ONLY IN CASE OF EMBEDDED TOMCAT DEPLOYMENT  ###
######___ ***** ENTER PATH TO YOUR STAND-ALONE TOMCAT SERVER ***** ____ ############

#catalina:
#  home: Path/to/your/external/tomcat
catalina:
  home: /home/f1soft/Softwares/tomcat

spring:
  profiles:
    active: rc
